#!/bin/bash

PREFIX="{{ PREFIX }}"

cd "$PREFIX" || exit

if [ $# -ne 1 ]; then
    echo "Need 1 Parameter"
    exit 1;
fi

if [ ! -f "./sites-enabled/${1}.conf" ]; then
    echo "No Site Found named ${1}"
    echo "Check if sites-enabled/${1}.conf exists"
    exit 2;
fi

rm "./sites-enabled/${1}.conf"
echo "Site Successfully Disabled"
